version: "3.8"

services:
  frontend:
    build:
      context: ./choponefront
      dockerfile: Dockerfile
    networks:
      - chopone_network
    expose:
      - "80"
    restart: unless-stopped

  backend:
    build:
      context: ./choponeback
      dockerfile: Dockerfile
    networks:
      - chopone_network
    expose:
      - "5000"
    volumes:
      - data:/app/data
    environment:
      - FLASK_ENV=production
      - DATA_DIR=/app/data
      - UPLOAD_FOLDER=/app/data/uploads
      - DOWNLOAD_FOLDER=/app/data/downloads
    restart: unless-stopped

networks:
  chopone_network:
    name: chopone_network
    external: true

volumes:
  data:
    name: chopone_data
