services:
  frontend:
    build:
      context: ./choponefront
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/dist
    networks:
      - chopone-network
    restart: unless-stopped

  backend:
    build:
      context: ./choponeback
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - data:/app/data
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/data/uploads
      - DOWNLOAD_FOLDER=/app/data/downloads
    networks:
      - chopone-network
    restart: unless-stopped

networks:
  chopone-network:
    driver: bridge
    name: chopone_network

volumes:
  data:
    name: chopone_data
  frontend_dist:
    name: chopone_frontend_dist
    external: true
