version: "3.8"

services:
  frontend:
    build:
      context: ./choponefront
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/dist
    restart: unless-stopped

  backend:
    build:
      context: ./choponeback
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - data:/app/data
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/data/uploads
      - DOWNLOAD_FOLDER=/app/data/downloads
    restart: unless-stopped

volumes:
  data:
    name: chopone_data
  frontend_dist:
    name: chopone_frontend_dist
    external: true
